name: drums
description: "A new Flutter project."
publish_to: 'none'

version: 0.4.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.2
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
